### ISSUE TITLE
Raster data

### ISSUE THREAD

**Issue by 2409950175** [joepeskett-dsc/rastervision_demo#2]
Hello, @joepeskett , i work on the chip_classification by RasterVision, your code is very helpful for me, thanks. I want ro run this script, but i have no relevant data. Can you give me some data? A small amount of data is also ok, thank you very much! My e-mail is 1402434282@qq.com.

**Comment by joepeskett** [comment]
@2409950175 sorry I didn't get back to you, I haven't kept track of this repo. If you head to Azavea's site, they have a list of data sources that you might want to use for a project. Hope that helps.
